from tkinter import *
root = Tk()
root.title('sample window')
root.geometry('500x400')
f = Frame(root, width=400, height=350, bg='blue', cursor='hand2')
f.propagate(0)
f.pack()
l1 = Label(f, text='username'), fg='red', width=8, height=2)
l1.place(x=200, y=70)
e1=Entry(root)
e1.grid(row=2,column=3)
l2 = Label(f, text='password', fg='red', width=8, height=2)
l2.place(x=200, y=140)
e2=Entry(root)
e2.grid(row=2,column=3)
root.mainloop()